MODEL:
  NAME: 'baseline'
  N_CHANNEL: 3
  N_CLASS: 10
  DEVICE: "cuda"
  DEVICE_IDS: "0d"
  BACKBONE: 'wrn40_4'
  DROPOUT: 0.0
  USE_NONLOCAL: False
  USE_SCSE: False
  USE_ATTENTION: False


INPUT:
  RESIZE_TRAIN: [36, 36]
  SIZE_TRAIN: [32, 32]
  RESIZE_TEST: [36, 36]
  SIZE_TEST: [32, 32]
  PROB: 0.5 # random horizontal flip
  RANDOM_ERASE:
    RE_PROB: 0.5 # random erasing
    RE_MAX_RATIO: 0.4
  USE_MIX_UP: False
  USE_CUT_MIX: False
  USE_AUGMIX: False
  USE_AUTOAUG: False
  PIXEL_MEAN: [0.28604059698879547, 0.28604059698879547, 0.28604059698879547]
  PIXEL_STD: [0.3202489254311618, 0.3202489254311618, 0.3202489254311618]
DATASETS:
  NAMES: ('competition')
  DATA_PATH: '/usr/demo/common_data'
  TRAIN:
    IMAGE_FOLDER: ''
  VAL:
    IMAGE_FOLDER: ''


DATALOADER:

  NUM_WORKERS: 2

SOLVER:
  OPTIMIZER_NAME: "Adam"
  SYNCBN: False

  BASE_LR: 3e-4
  BIAS_LR_FACTOR: 1

  MOMENTUM: 0.9

  USE_WARMUP: True
  MIN_LR: 3e-6

  WEIGHT_DECAY: 5e-4
  WEIGHT_DECAY_BIAS: 5e-4

  GAMMA: 0.1
  STEPS: [40, 70]

  WARMUP_FACTOR: 0.01
  WARMUP_EPOCH: 10
  WARMUP_BEGAIN_LR: 3e-05
  WARMUP_METHOD: "linear"

  MAX_EPOCHS: 400
  CHECKPOINT_PERIOD: 1
  LOG_PERIOD: 100
  EVAL_PERIOD: 1
  START_SAVE_EPOCH: 300

  PER_BATCH: 128
  TENSORBOARD:
    USE: True
    LOG_PERIOD: 20
  RESUME: False
  RESUME_CHECKPOINT: ''


OUTPUT_DIR: "../work_dirs/baseline/"